#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Only run tests locally, not in CI.
if [ "$GITHUB_ACTIONS" != "true" ]; then
  (cd .. && ./gradlew :widgets:testDebugUnitTest) || exit 1
  # Only run lint and tests locally, not in CI

  # Checks secret leaks in the commits that are being pushed
  gitleaks detect --log-opts="@{u}..HEAD"
fi
